"""Move domain sort order to topic

Revision ID: 2b2fe4b939eb
Revises: 3c92851e5a34
Create Date: 2026-03-22 19:18:24.457434

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b2fe4b939eb"
down_revision = "3c92851e5a34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_items", schema=None) as batch_op:
        batch_op.drop_column("domain_sort_order")

    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("domain_sort_order", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_column("domain_sort_order")

    with op.batch_alter_table("task_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("domain_sort_order", sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
