"""Add topic sort order to task item

Revision ID: 3c92851e5a34
Revises: 4a25df22455d
Create Date: 2026-03-22 19:09:11.541881

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c92851e5a34"
down_revision = "4a25df22455d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("topic_sort_order", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_items", schema=None) as batch_op:
        batch_op.drop_column("topic_sort_order")

    # ### end Alembic commands ###
